pipeline {
    agent any


    environment { 
        VENV = "${WORKSPACE}/venv" 
        DOCKER_IMAGE = "sipho/messaging_app:latest" } 

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/Msaination/alx-backend-python.git'
            }
        }

        stage('Setup Python Env') {
            steps {
                sh '''
                python3 -m venv $VENV
                source $VENV/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                source $VENV/bin/activate
                pytest --junitxml=reports/junit.xml --html=reports/report.html --self-contained-html
                '''
            }
        }


        stage('Build Docker Image') { 
            steps { 
                sh '''
                 docker build -t $DOCKER_IMAGE . 
                ''' 
            } 
        } 
        stage('Push Docker Image') { 
            steps { 
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) { 
                    sh ''' echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin docker push $DOCKER_IMAGE 
                    ''' 
                } 
            } 
        }
        stage('Publish Report') {
            steps {
                junit 'reports/junit.xml'
                publishHTML(target: [
                    reportDir: 'reports',
                    reportFiles: 'report.html',
                    reportName: 'Pytest Report'
                ])
            }
        }
    }

    triggers {
        // Manual trigger only (no SCM polling or cron)
    }
}
